feat(cockroachdb metrics and logs plugin)
observIQ/observiq-otel-collector pull request #1039
Opened 2023-04-25 21:30 UTC by BominRahmani

The following is a plugin for CockroachDB that collects metrics and logs. This version is strictly for the dedicated/local version of cockroachDB.

# Example config for Metrics
<img width="697" alt="image" src="https://user-images.githubusercontent.com/38274348/234408035-661b6bce-2196-4a16-842b-ed255a4ca275.png">

# Example config for Logs
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/38274348/234408397-c9a2f5fa-22e0-480d-9c2a-11ebdeb4f1ec.png">

2023-04-25 21:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/observIQ/observiq-otel-collector?pullRequest=1039) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/observIQ/observiq-otel-collector?pullRequest=1039) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/observIQ/observiq-otel-collector?pullRequest=1039) it.</sub>

2023-05-05 14:30 UTC, dehaansa reviewed
Few comments, overall looks good.

2023-05-05 14:30 UTC, dehaansa commented on plugins/cockroachdb_logs.yaml
> +    description: The absolute path to the CockroachDB Dev Logs
Should refer to these as dev logs or developer logs consistently between the different parameters.

2023-05-05 14:30 UTC, dehaansa commented on plugins/cockroachdb_logs.yaml
> +          - filelog/health_logs
Should all of these named be prefixed with cockroachdb? IE `filelog/cockroachdb_health_logs`

2023-05-11 13:53 UTC, dehaansa approved these changes

2023-05-11 13:56 UTC, cpheps commented
@BominRahmani Can you do the following before we review:
- Run `make create-plugin-docs` that should resolve the `check-plugin-docs` step
- Rebase on `release/v1.25.0` branch
- Include samples of the collected logs in the PR description

2023-05-15 17:34 UTC, cpheps commented on plugins/cockroachdb_logs.yaml
> +    default: UTC
Can we add the [offset_storage_dir](https://github.com/observIQ/observiq-otel-collector/blob/release/v1.25.0/plugins/macos_logs.yaml#L30-L33) into here as well?

2023-05-15 17:34 UTC, cpheps commented on plugins/cockroachdb_logs.yaml
> +    {{ end }} ## End Health Logs.
nit: remove the `## End health logs`

2023-05-15 17:34 UTC, cpheps commented on plugins/cockroachdb_logs.yaml
> +    {{ end }} ## End of dev logs.
nit: Remove the comment

2023-05-15 17:34 UTC, cpheps commented on plugins/cockroachdb_logs.yaml
> +    {{ end }} # End of sql schema logs
nit: Same here

2023-05-15 17:34 UTC, cpheps commented on plugins/cockroachdb_logs.yaml
> +    {{ end }} # End of telemetry logs
nit: Same here

2023-05-15 17:34 UTC, cpheps commented on plugins/cockroachdb_logs.yaml
> +    {{ end }} # End of kv distribution logs
nit: Same here

2023-05-15 17:34 UTC, cpheps commented on plugins/cockroachdb_logs.yaml
> +    {{ end }} # End of pebble logs.
nit: Same here

2023-05-15 18:06 UTC, cpheps commented on plugins/cockroachdb_logs.yaml
> +    default: beginning
default should be `end`

2023-05-15 18:15 UTC, cpheps commented on plugins/cockroachdb_logs.yaml
> +    default: UTC
Can we also add the `parse_to` and `retain_raw_logs` fields like we do [here](https://github.com/observIQ/observiq-otel-collector/blob/release/v1.25.0/plugins/mongodb_logs.yaml#L18-L28)

2023-05-15 18:17 UTC, cpheps requested changes

2023-05-15 18:17 UTC, cpheps commented on plugins/cockroachdb_logs.yaml
> +          severity:
I think the severities need a mapping. They are showing as unspecified for me. An example is [here](https://github.com/observIQ/observiq-otel-collector/blob/release/v1.25.0/plugins/apache_http_logs.yaml#L74-L81)

2023-06-01 12:48 UTC, cpheps requested changes

2023-06-01 12:48 UTC, cpheps commented on plugins/cockroachdb_logs.yaml
> +  - name: parse_to
Parse too is not actually being used it looks like. See apache combined as an example how it is used to set the initial parsing [here](https://github.com/observIQ/observiq-otel-collector/blob/release/v1.26.0/plugins/apache_combined_logs.yaml#L47) and that changes how you reference fields later on like [here](https://github.com/observIQ/observiq-otel-collector/blob/release/v1.26.0/plugins/apache_combined_logs.yaml#L52)

2023-06-01 12:48 UTC, cpheps commented on plugins/cockroachdb_logs.yaml
> +  - name: retain_raw_logs
This is not used either see how it is used here [here](https://github.com/observIQ/observiq-otel-collector/blob/release/v1.26.0/plugins/apache_combined_logs.yaml#L39-L44) to save off the body) then again [here](https://github.com/observIQ/observiq-otel-collector/blob/release/v1.26.0/plugins/apache_combined_logs.yaml#L59-L64) to re add it at the end.

2023-06-01 12:48 UTC, cpheps commented on plugins/cockroachdb_logs.yaml
> +  - name: offset_storage_dir
This needs to be set as an extension before the receivers like [here](https://github.com/observIQ/observiq-otel-collector/blob/release/v1.26.0/plugins/iis_logs.yaml#L72-L74). Then is needs to be referenced in each `filelog` receiver like [here](https://github.com/observIQ/observiq-otel-collector/blob/release/v1.26.0/plugins/iis_logs.yaml#L79)

2023-06-02 16:56 UTC, cpheps commented on plugins/cockroachdb_logs.yaml
> +        {{ end }}
This raw logs block and the one at the end to move it if `parse_to` is `body` needs to be on every filelog receiver.

2023-06-07 18:49 UTC, cpheps requested changes

2023-06-09 12:49 UTC, cpheps approved these changes

2023-06-09 12:49 UTC, merged