fix: Upgrade gonum.org/v1/gonum
observIQ/observiq-otel-collector pull request #317
Opened 2022-03-28 20:40 UTC by antonblock

### Proposed Change

Upgrade gonum.org/v1/gonum in the main module and `logsreceiver`. The upgrade was already merged in `opentelemetry-log-collection` (https://github.com/open-telemetry/opentelemetry-log-collection/pull/437https://github.com/open-telemetry/opentelemetry-log-collection/pull/437), but we were still referencing the broken version here.

Before the fix, running tests would result in this segfault:

```
unexpected fault address 0x1074c57dc
fatal error: fault
[signal SIGBUS: bus error code=0x1 addr=0x1074c57dc pc=0x104712538]

goroutine 97 [running]:
runtime.throw({0x108a3e2af?, 0x7f?})
	/opt/homebrew/Cellar/go/1.18/libexec/src/runtime/panic.go:992 +0x50 fp=0xc0009a83a0 sp=0xc0009a8370 pc=0x10473ae10
runtime.sigpanic()
	/opt/homebrew/Cellar/go/1.18/libexec/src/runtime/signal_unix.go:815 +0x124 fp=0xc0009a83d0 sp=0xc0009a83a0 pc=0x104753514
runtime.mapiterinit(0x10a5b5560?, 0xc000565680, 0x1074c57cc)
	/opt/homebrew/Cellar/go/1.18/libexec/src/runtime/map.go:821 +0x68 fp=0xc0009a8410 sp=0xc0009a83e0 pc=0x104712538
reflect.mapiterinit(0x30000000008478?, 0x30?, 0x137991bb8?)
	/opt/homebrew/Cellar/go/1.18/libexec/src/runtime/map.go:1373 +0x20 fp=0xc0009a8440 sp=0xc0009a8410 pc=0x1047690d0
gonum.org/v1/gonum/graph/iterator.(*mapIter).next(0xc000610a30)
	/Users/nico/go/pkg/mod/gonum.org/v1/gonum@v0.9.3/graph/iterator/map.go:89 +0xcc fp=0xc0009a8480 sp=0xc0009a8440 pc=0x1074c57dc
gonum.org/v1/gonum/graph/iterator.(*Nodes).Next(0xc0005657d0)
	/Users/nico/go/pkg/mod/gonum.org/v1/gonum@v0.9.3/graph/iterator/nodes_map.go:40 +0x78 fp=0xc0009a84d0 sp=0xc0009a8480 pc=0x1074c5988
github.com/open-telemetry/opentelemetry-log-collection/pipeline.connectNodes(0xc0001235c0)
	/Users/nico/go/pkg/mod/github.com/open-telemetry/opentelemetry-log-collection@v0.24.0/pipeline/directed.go:100 +0x254 fp=0xc0009a8610 sp=0xc0009a84d0 pc=0x10763c8c4
github.com/open-telemetry/opentelemetry-log-collection/pipeline.NewDirectedPipeline({0xc0001235a0, 0x2, 0x2})
	/Users/nico/go/pkg/mod/github.com/open-telemetry/opentelemetry-log-collection@v0.24.0/pipeline/directed.go:181 +0x218 fp=0xc0009a86e0 sp=0xc0009a8610 pc=0x10763d868
github.com/open-telemetry/opentelemetry-log-collection/pipeline.Config.BuildPipeline({0xc000610920, 0x1, 0x1}, {0x0, 0xc000610970, {0x109efb82a, 0x1}, {0x10de8bb30, 0x0, 0x0}, ...}, ...)
	/Users/nico/go/pkg/mod/github.com/open-telemetry/opentelemetry-log-collection@v0.24.0/pipeline/config.go:89 +0xd8 fp=0xc0009a87c0 sp=0xc0009a86e0 pc=0x10763b6c8
github.com/open-telemetry/opentelemetry-log-collection/agent.(*LogAgentBuilder).Build(0xc0009a8d10)
	/Users/nico/go/pkg/mod/github.com/open-telemetry/opentelemetry-log-collection@v0.24.0/agent/builder.go:102 +0x46c fp=0xc0009a8b00 sp=0xc0009a87c0 pc=0x10764517c
github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza.createLogsReceiver.func1({0xc000c7aef8?, 0x104754ddc?}, {{0xc0001f9e00, {0x10ae53068, 0xc0004c6fc0}, {0x10ae5cc48, 0x10de8bb30}, 0x0}, {{0x16b6ff9a8, 0x58}, ...}}, ...)
	/Users/nico/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza@v0.45.1/factory.go:81 +0x794 fp=0xc0009a8e50 sp=0xc0009a8b00 pc=0x1079fd414
go.opentelemetry.io/collector/component.CreateLogsReceiverFunc.CreateLogsReceiver(...)
	/Users/nico/go/pkg/mod/go.opentelemetry.io/collector@v0.46.0/component/receiver.go:191
go.opentelemetry.io/collector/component.(*receiverFactory).CreateLogsReceiver(0xc000a9a540?, {0x10ae7d908?, 0xc0001a8018?}, {{0xc0001f9e00, {0x10ae53068, 0xc0004c6fc0}, {0x10ae5cc48, 0x10de8bb30}, 0x0}, {{0x16b6ff9a8, ...}, ...}}, ...)
	<autogenerated>:1 +0x100 fp=0xc0009a8f70 sp=0xc0009a8e50 pc=0x104dfae50
go.opentelemetry.io/collector/service/internal/builder.attachReceiverToPipelines({0x10ae7d908, 0xc0001a8018}, {{0xc0001f9e00, {0x10ae53068, 0xc0004c6fc0}, {0x10ae5cc48, 0x10de8bb30}, 0x0}, {{0x16b6ff9a8, 0x58}, ...}}, ...)
	/Users/nico/go/pkg/mod/go.opentelemetry.io/collector@v0.46.0/service/internal/builder/receivers_builder.go:191 +0xb94 fp=0xc0009a92d0 sp=0xc0009a8f70 pc=0x104e5f6d4
go.opentelemetry.io/collector/service/internal/builder.(*receiversBuilder).buildReceiver(0xc000c7b660, {0x10ae7d908, 0xc0001a8018}, {{0xc0001f9e00, {0x10ae53068, 0xc0004c6fc0}, {0x10ae5cc48, 0x10de8bb30}, 0x0}, {{0x16b6ff9a8, ...}, ...}}, ...)
	/Users/nico/go/pkg/mod/go.opentelemetry.io/collector@v0.46.0/service/internal/builder/receivers_builder.go:257 +0x34c fp=0xc0009a9530 sp=0xc0009a92d0 pc=0x104e5faec
go.opentelemetry.io/collector/service/internal/builder.BuildReceivers({0xc0001f9b60, {0x10ae53068, 0xc0004c6fc0}, {0x10ae5cc48, 0x10de8bb30}, 0x0}, {{0x16b6ff9a8, 0x58}, {0x108af1573, 0x2f}, ...}, ...)
	/Users/nico/go/pkg/mod/go.opentelemetry.io/collector@v0.46.0/service/internal/builder/receivers_builder.go:109 +0x3ec fp=0xc0009a9840 sp=0xc0009a9530 pc=0x104e5e4dc
go.opentelemetry.io/collector/service.newService(0xc000c7bcc0)
	/Users/nico/go/pkg/mod/go.opentelemetry.io/collector@v0.46.0/service/service.go:74 +0x8b0 fp=0xc0009a9b60 sp=0xc0009a9840 pc=0x10508b950
go.opentelemetry.io/collector/service.(*Collector).setupConfigurationComponents(0xc000c66000, {0x10ae7d908, 0xc0001a8018})
	/Users/nico/go/pkg/mod/go.opentelemetry.io/collector@v0.46.0/service/collector.go:200 +0x414 fp=0xc0009a9d60 sp=0xc0009a9b60 pc=0x105088d74
go.opentelemetry.io/collector/service.(*Collector).Run(0xc000c66000, {0x10ae7d908, 0xc0001a8018})
	/Users/nico/go/pkg/mod/go.opentelemetry.io/collector@v0.46.0/service/collector.go:240 +0x30c fp=0xc0009a9ef0 sp=0xc0009a9d60 pc=0x10508917c
github.com/observiq/observiq-otel-collector/collector.(*collector).Run.func1()
	/Users/nico/observiq/observiq-otel-collector/collector/collector.go:90 +0x94 fp=0xc0009a9fd0 sp=0xc0009a9ef0 pc=0x1089fcb24
runtime.goexit()
	/opt/homebrew/Cellar/go/1.18/libexec/src/runtime/asm_arm64.s:1259 +0x4 fp=0xc0009a9fd0 sp=0xc0009a9fd0 pc=0x10476fe04
created by github.com/observiq/observiq-otel-collector/collector.(*collector).Run
	/Users/nico/observiq/observiq-otel-collector/collector/collector.go:88 +0x4fc
```

Addresses https://app.vivifyscrum.com/boards/112100/TTB0-591

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-03-28 21:36 UTC, BinaryFissionGames approved these changes

2022-03-28 23:36 UTC, cpheps requested changes

2022-03-28 23:36 UTC, cpheps commented on go.sum
> +gonum.org/v1/gonum v0.11.0 h1:f1IJhK4Km5tBJmaiJXtk/PkL4cdVX6J+tGiM187uT5E=
Can we run `make tidy` on these to clean out the old versions?

2022-03-29 13:13 UTC, cpheps approved these changes

2022-03-29 13:39 UTC, merged