feat: iis example config for google cloud exporter
observIQ/observiq-otel-collector pull request #405
Opened 2022-05-10 18:13 UTC by algchoo

### Proposed Change

Added example configuration using iis receiver and exporting to google cloud
* tested configuration on Windows Server 2019

##### Checklist
- [x] Changes are tested
- [ ] CI has passed

2022-05-10 18:18 UTC, jsirianni requested changes

2022-05-10 18:18 UTC, jsirianni commented on config/google_cloud_exporter/iis/config.yaml
> +    collection_interval: 10s
Lets be consistent with 60s collection interval. I believe the Google minimum is 30 seconds.

2022-05-10 18:18 UTC, jsirianni commented on config/google_cloud_exporter/iis/config.yaml
> +processors:
We probably need resource detection, resource, and resource attributes transposer here. I am curious to see how the metrics look into the metric explorer.

2022-05-10 18:22 UTC, BinaryFissionGames commented on config/google_cloud_exporter/iis/config.yaml
> +        target_type: generic_node
Now that v0.6.0 is released, we can simplify these a LOT. The exporter now has:
- Built in normalize sums processor (doesn't need to be configured separately)
- Built in Batch processor (doesn't need to be configured separately)
- Automatic mapping to generic_node
- metric prefix is default set to "workload.googleapis.com"
- retry_on_failure is default disabled

I think from now on, we should try using the new exporter defaults with these configs.

Let me know if any of that was unclear.

https://github.com/observIQ/observiq-otel-collector/tree/main/exporter/googlecloudexporter

2022-05-10 18:24 UTC, jsirianni commented on config/google_cloud_exporter/iis/config.yaml
> +processors:
See Brandon's comment

2022-05-10 23:57 UTC, cpheps approved these changes

2022-05-10 23:59 UTC, BinaryFissionGames approved these changes

2022-05-11 13:13 UTC, jsirianni approved these changes

2022-05-11 13:13 UTC, merged