Added plugin receiver docs folder
observIQ/observiq-otel-collector pull request #610
Opened 2022-08-02 17:27 UTC by asenkowski

### Proposed Change
Added plugins folder to docs for plugin receiver documentation.

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2022-08-02 17:55 UTC, StefanKurek approved these changes

2022-08-02 19:06 UTC, BinaryFissionGames requested changes
Tried to be thorough on all the differences I can see here between these docs and the actual plugins (although I'm sure I missed some); It turns out there are quite a few, which makes sense, since they are all based off the stanza docs.

2022-08-02 19:06 UTC, BinaryFissionGames commented on docs/plugins/syslog.md
> +
We should also document:
- `data_flow` parameter
- `max_log_size` parameter

2022-08-02 19:06 UTC, BinaryFissionGames commented on docs/plugins/tomcat.md
> +| `source` | `file` | Use this field to specify where your logs are coming from. When choosing the 'file' option, the agent reads in logs from the log paths specified below. When choosing the 'Kubern
No k8s support
```suggestion
```

2022-08-02 19:06 UTC, BinaryFissionGames commented on docs/plugins/tomcat.md
> +| `log_format` | `default`  | When choosing the 'default' option, the agent will expect and parse logs in a format that matches the default logging configuration. When choosing the 'observIQ' option,
Looks like the alternate log format was dropped too
```suggestion
```

2022-08-02 19:06 UTC, BinaryFissionGames commented on docs/plugins/tomcat.md
> +| `container_name` | `"*"` | The container name of the Nginx container. Only relevant if the source is "kubernetes". |
```suggestion
```

2022-08-02 19:06 UTC, BinaryFissionGames commented on docs/plugins/tomcat.md
> +| `start_at` | `end` | Start reading file from 'beginning' or 'end' |
Also has a timezone param
```suggestion
| `start_at` | `end` | Start reading file from 'beginning' or 'end' |
| `timezone` | `timezone` | `UTC` | Timezone to use when parsing the timestamp |
```

2022-08-03 12:15 UTC, cpheps commented on docs/plugins/active_directory.md
> +# `active_directory` plugin
I agree with @BinaryFissionGames. If we do want a single file we should split it into a logs and metrics section. Possibly others if we have specific use case plugins down the road.

2022-08-03 12:18 UTC, cpheps commented on docs/plugins/active_directory.md
> +| `start_at` | `enum` | `end` | Start reading file from 'beginning' or 'end' |
In the [parameter types](https://github.com/observIQ/observiq-otel-collector/tree/main/receiver/pluginreceiver#parameters) for the plugin receiver docs we don't call out enums. We also don't have great documentation on writing your own plugin but that's a separate issue.

Just saying `string` for the type and listing possible values should be good. As long as it's hard for the user to make a mistake.

2022-10-20 12:23 UTC, cpheps commented
Closing this as we're currently working on a way to autogenerate documentation.

2022-10-20 12:23 UTC, closed without merging