bug: attempt hotfix for windows eventlog receiver
observIQ/observiq-otel-collector pull request #865
Opened 2022-12-28 21:00 UTC by schmikei

Attempting to never resize a buffer to a size of 0, may not be the best approach so going to keep in draft. Confirmed that this works by exporting to file.

<details>
<summary> snippet </summary>

```json
{"resourceLogs":[{"resource":{},"scopeLogs":[{"scope":{},"logRecords":[{"timeUnixNano":"1672260914889548900","observedTimeUnixNano":"1672260915658423400","severityNumber":9,"severityText":"INFO","body":{"kvlistValue":{"values":[{"key":"system_time","value":{"stringValue":"2022-12-28T20:55:14.889548900Z"}},{"key":"channel","value":{"stringValue":"System"}},{"key":"record_id","value":{"intValue":"2022"}},{"key":"level","value":{"stringValue":"Information"}},{"key":"event_data","value":{"arrayValue":{"values":[{"stringValue":"observIQ Distro for OpenTelemetry Collector"},{"stringValue":"running"}]}}},{"key":"provider","value":{"kvlistValue":{"values":[{"key":"guid","value":{"stringValue":"{555908d1-a6d7-4695-8e1e-26931d2012f4}"}},{"key":"event_source","value":{"stringValue":"Service Control Manager"}},{"key":"name","value":{"stringValue":"Service Control Manager"}}]}}},{"key":"computer","value":{"stringValue":"keith-windows-panic-box"}},{"key":"message","value":{"stringValue":"The observIQ Distro for OpenTelemetry Collector service entered the running state."}},{"key":"task","value":{"stringValue":"0"}},{"key":"opcode","value":{"stringValue":"0"}},{"key":"keywords","value":{"arrayValue":{"values":[{"stringValue":"Classic"}]}}},{"key":"event_id","value":{"kvlistValue":{"values":[{"key":"qualifiers","value":{"intValue":"16384"}},{"key":"id","value":{"intValue":"7036"}}]}}}]}},"traceId":"","spanId":""}]}]}]}
{"resourceLogs":[{"resource":{},"scopeLogs":[{"scope":{},"logRecords":[{"timeUnixNano":"1672260964860499200","observedTimeUnixNano":"1672260966671984900","severityNumber":9,"severityText":"INFO","body":{"kvlistValue":{"values":[{"key":"event_id","value":{"kvlistValue":{"values":[{"key":"qualifiers","value":{"intValue":"16384"}},{"key":"id","value":{"intValue":"7040"}}]}}},{"key":"computer","value":{"stringValue":"keith-windows-panic-box"}},{"key":"record_id","value":{"intValue":"2023"}},{"key":"task","value":{"stringValue":"0"}},{"key":"keywords","value":{"arrayValue":{"values":[{"stringValue":"Classic"}]}}},{"key":"provider","value":{"kvlistValue":{"values":[{"key":"event_source","value":{"stringValue":"Service Control Manager"}},{"key":"name","value":{"stringValue":"Service Control Manager"}},{"key":"guid","value":{"stringValue":"{555908d1-a6d7-4695-8e1e-26931d2012f4}"}}]}}},{"key":"system_time","value":{"stringValue":"2022-12-28T20:56:04.860499200Z"}},{"key":"channel","value":{"stringValue":"System"}},{"key":"level","value":{"stringValue":"Information"}},{"key":"message","value":{"stringValue":"The start type of the Background Intelligent Transfer Service service was changed from auto start to demand start."}},{"key":"opcode","value":{"stringValue":"0"}},{"key":"event_data","value":{"arrayValue":{"values":[{"stringValue":"Background Intelligent Transfer Service"},{"stringValue":"auto start"},{"stringValue":"demand start"},{"stringValue":"BITS"}]}}}]}},"traceId":"","spanId":""},{"timeUnixNano":"1672260964918012100","observedTimeUnixNano":"1672260966671984900","severityNumber":9,"severityText":"INFO","body":{"kvlistValue":{"values":[{"key":"event_id","value":{"kvlistValue":{"values":[{"key":"id","value":{"intValue":"7036"}},{"key":"qualifiers","value":{"intValue":"16384"}}]}}},{"key":"provider","value":{"kvlistValue":{"values":[{"key":"name","value":{"stringValue":"Service Control Manager"}},{"key":"guid","value":{"stringValue":"{555908d1-a6d7-4695-8e1e-26931d2012f4}"}},{"key":"event_source","value":{"stringValue":"Service Control Manager"}}]}}},{"key":"message","value":{"stringValue":"The Background Intelligent Transfer Service service entered the stopped state."}},{"key":"task","value":{"stringValue":"0"}},{"key":"opcode","value":{"stringValue":"0"}},{"key":"event_data","value":{"arrayValue":{"values":[{"stringValue":"Background Intelligent Transfer Service"},{"stringValue":"stopped"}]}}},{"key":"system_time","value":{"stringValue":"2022-12-28T20:56:04.918012100Z"}},{"key":"computer","value":{"stringValue":"keith-windows-panic-box"}},{"key":"channel","value":{"stringValue":"System"}},{"key":"record_id","value":{"intValue":"2024"}},{"key":"level","value":{"stringValue":"Information"}},{"key":"keywords","value":{"arrayValue":{"values":[{"stringValue":"Classic"}]}}}]}},"traceId":"","spanId":""}]}]}]}
{"resourceLogs":[{"resource":{},"scopeLogs":[{"scope":{},"logRecords":[{"timeUnixNano":"1672261005578990700","observedTimeUnixNano":"1672261005682803300","severityNumber":9,"severityText":"INFO","body":{"kvlistValue":{"values":[{"key":"computer","value":{"stringValue":"keith-windows-panic-box"}},{"key":"level","value":{"stringValue":"4"}},{"key":"opcode","value":{"stringValue":""}},{"key":"keywords","value":{"arrayValue":{"values":[{"stringValue":"0x80000000000000"}]}}},{"key":"event_data","value":{"arrayValue":{"values":[{"stringValue":"Service stopped"}]}}},{"key":"event_id","value":{"kvlistValue":{"values":[{"key":"qualifiers","value":{"intValue":"0"}},{"key":"id","value":{"intValue":"0"}}]}}},{"key":"provider","value":{"kvlistValue":{"values":[{"key":"name","value":{"stringValue":"gupdate"}},{"key":"guid","value":{"stringValue":""}},{"key":"event_source","value":{"stringValue":""}}]}}},{"key":"record_id","value":{"intValue":"26185"}},{"key":"message","value":{"stringValue":""}},{"key":"task","value":{"stringValue":"0"}},{"key":"system_time","value":{"stringValue":"2022-12-28T20:56:45.578990700Z"}},{"key":"channel","value":{"stringValue":"Application"}}]}},"traceId":"","spanId":""}]}]}]}
{"resourceLogs":[{"resource":{},"scopeLogs":[{"scope":{},"logRecords":[{"timeUnixNano":"1672261005210359900","observedTimeUnixNano":"1672261006660590400","severityNumber":9,"severityText":"INFO","body":{"kvlistValue":{"values":[{"key":"system_time","value":{"stringValue":"2022-12-28T20:56:45.210359900Z"}},{"key":"record_id","value":{"intValue":"2025"}},{"key":"task","value":{"stringValue":"0"}},{"key":"keywords","value":{"arrayValue":{"values":[{"stringValue":"Classic"}]}}},{"key":"level","value":{"stringValue":"Information"}},{"key":"message","value":{"stringValue":"The Google Update Service (gupdate) service entered the running state."}},{"key":"opcode","value":{"stringValue":"0"}},{"key":"event_data","value":{"arrayValue":{"values":[{"stringValue":"Google Update Service (gupdate)"},{"stringValue":"running"}]}}},{"key":"event_id","value":{"kvlistValue":{"values":[{"key":"qualifiers","value":{"intValue":"16384"}},{"key":"id","value":{"intValue":"7036"}}]}}},{"key":"provider","value":{"kvlistValue":{"values":[{"key":"name","value":{"stringValue":"Service Control Manager"}},{"key":"guid","value":{"stringValue":"{555908d1-a6d7-4695-8e1e-26931d2012f4}"}},{"key":"event_source","value":{"stringValue":"Service Control Manager"}}]}}},{"key":"computer","value":{"stringValue":"keith-windows-panic-box"}},{"key":"channel","value":{"stringValue":"System"}}]}},"traceId":"","spanId":""},{"timeUnixNano":"1672261005578990700","observedTimeUnixNano":"1672261006663541500","severityNumber":9,"severityText":"INFO","body":{"kvlistValue":{"values":[{"key":"task","value":{"stringValue":"0"}},{"key":"keywords","value":{"arrayValue":{"values":[{"stringValue":"Classic"}]}}},{"key":"system_time","value":{"stringValue":"2022-12-28T20:56:45.578990700Z"}},{"key":"computer","value":{"stringValue":"keith-windows-panic-box"}},{"key":"channel","value":{"stringValue":"System"}},{"key":"record_id","value":{"intValue":"2026"}},{"key":"level","value":{"stringValue":"Information"}},{"key":"message","value":{"stringValue":"The Google Update Service (gupdate) service entered the stopped state."}},{"key":"event_id","value":{"kvlistValue":{"values":[{"key":"id","value":{"intValue":"7036"}},{"key":"qualifiers","value":{"intValue":"16384"}}]}}},{"key":"provider","value":{"kvlistValue":{"values":[{"key":"name"," [...]

2023-01-03 13:11 UTC, cpheps commented
@schmikei do you mind linking the changed code in the PR?

2023-01-03 14:27 UTC, schmikei commented
> @schmikei do you mind linking the changed code in the PR?

Edited it ✅

2023-01-03 20:24 UTC, schmikei commented
@BinaryFissionGames @cpheps 

Here is the diff I think that should work, i.e. return an error on `bufferUsed` of 0 

https://github.com/open-telemetry/opentelemetry-collector-contrib/compare/main...observIQ:opentelemetry-collector-contrib:windows-event-log-panic-pt-3?expand=1

2023-01-03 20:34 UTC, BinaryFissionGames commented
@schmikei The fix looks good to me; Should we also add similar logic to the `RenderSimple` function, just in case the same scenario can happen there too?

2023-01-03 20:49 UTC, schmikei commented
> @schmikei The fix looks good to me; Should we also add similar logic to the `RenderSimple` function, just in case the same scenario can happen there too?

Sure better to be safe than sorry at this point 👍

2023-01-04 13:01 UTC, cpheps commented
I think this looks good can you rebase the branch? After that I'll generate a hotfix MSI.

2023-01-04 13:45 UTC, cpheps requested changes
We don't want this merged into main but to stay on the `windows-panic-fix` branch so we can test hot fixes. If it works we'll upstream the fix into OTel.

2023-01-09 13:18 UTC, cpheps commented
Closing as we don't want this to be a real PR and we had to mock up a new branch with fixes for 1.15.0.

2023-01-09 13:18 UTC, closed without merging